version: '3.8'

services:
  frontend:
    container_name: client
    restart: on-failure
    ports:
      - "8080:8080"
    build:
      context: ./client
      dockerfile: Dockerfile

  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db

  backend:
    container_name: server
    restart: on-failure
    build:
      context: ./server
      target: prod
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db




