FROM node:18-alpine

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/

COPY package.json package-lock.json ./

ENV PATH /opt/node_modules/.bin:$PATH

RUN npm install --only=production

WORKDIR /opt/app

COPY . .

RUN npm run build

EXPOSE 1337

CMD ["npm", "run", "start"]
